### ISSUE TITLE
Reduce the number of iron.io api request

### ISSUE THREAD

**Issue by maxfrigge** [assaf/ironium#17]
I have had 360k API request on iron.io and there have only been 149 messages. Any idea what's causing all those requests?

**Comment by djanowski** [comment]
What version of Ironium?

**Comment by maxfrigge** [comment]
Still on 2.6.0

**Comment by assaf** [comment]
Polling for new messages: ~120K API requests per month per queue.

**Comment by maxfrigge** [comment]
Ok - just to avoid any confusion - polling for new messages is triggered by `ironium.queue('jobs').eachJob()` in combination with `ironium.start()`. So if I have s single instance of my worker calling `ironium.queue('jobs').eachJob()` exactly once, it should be using around ~120K API requests per month.

This is exactly the setup I am running right now and last month it was ~360K API requests.

**Comment by assaf** [comment]
That's correct

**Comment by maxfrigge** [comment]
Ok.. very strange though that I get tripple of that. I will upgrade to 2.7.0 and report back next month if I am still getting the 360K requests.

**Comment by maxfrigge** [comment]
Just wanted to report back. Running on the latest version I am having about 150K request per month.

**Comment by djanowski** [comment]
@maxfrigge Thank you!
