### ISSUE TITLE
Bulk loading jobs

### ISSUE THREAD

**Issue by KyleAMathews** [assaf/ironium#19]
I'm looking at using Iron.io to do bulk processing for 100s of thousands of micro-jobs. Is there a way to bulk-upload jobs as well as letting a worker grab multiple jobs at a time?

Nice work on this library btw! Been enjoying poking around your code/docs.

**Comment by assaf** [comment]
There's no bulk API. I'm not sure IronMQ is ideal for that use case, with HTTP and persistence, there's a noticeable overhead on each job. If you need low latency but don't care about persistence, 0MQ would be better. Otherwise, I would recommend queuing and performing batch jobs.

**Comment by KyleAMathews** [comment]
Hmmm... ok—the reason I ask is the official node.js client supports getting up to 100 messages at a time so I assumed this library would support it as well https://github.com/iron-io/iron_mq_node#reserveget-messages-from-a-queue

Batching jobs together would work well for my use case.

Lower latency would be nice but I'm a one-man programming band atm so trying to avoid running services when I can :)

thanks!

**Comment by djanowski** [comment]
4.0 now processes jobs concurrently and allows queuing multiple jobs at a time.
