### ISSUE TITLE
Errors in workers are caught and discarded

### ISSUE THREAD

**Issue by KyleAMathews** [assaf/ironium#20]
Which makes debugging them not very fun. I'm assuming one of your promises are catching them? Could we rethrow caught errors from workers?

**Comment by assaf** [comment]
All errors are logged: https://github.com/assaf/ironium#logging

**Comment by KyleAMathews** [comment]
Hmmm... gotcha. Makes sense—just wasn't expecting it during dev. I'll add an `onerror` handler. Thanks.
