### ISSUE TITLE
Long running jobs (> 10m)

### ISSUE THREAD

**Issue by maxfrigge** [assaf/ironium#27]
Is there a way to deal with long running jobs, that would take longer then 10 minutes to complete?

**Comment by assaf** [comment]
If you want error handling and retry: break long jobs into smaller/shorter jobs.

If you don't care about rety, call the callback to tell Ironium it can delete the job, and then the code can run as long as it needs.

**Comment by maxfrigge** [comment]
I thought the timeout is set by ironium.
Shouldn't the default iron.io timeout be 60m?

**Comment by assaf** [comment]
Iron.io has a default, but Ironium sets it to 10 minutes. Ironium doesn't have its own storage, so if the process restarts (read: every deploy), it forgets all in-progress jobs, and it has to wait for Iron.io to time them out and place them back in the queue. 60 minute timeout means every time we deploy, some jobs would take longer than 60 minutes to complete.

**Comment by maxfrigge** [comment]
Ok get it. Would you mind having the timeout as config param?

**Comment by assaf** [comment]
That would work. I hard-coded all the values, but most of them could move into configuration with a sane default.

**Comment by djanowski** [comment]
PR will be welcome. Thanks.
