### ISSUE TITLE
DoS when not calling callback on schedules job

### ISSUE THREAD

**Issue by sheerun** [assaf/ironium#34]
So first I create a scheduled job that never calls `callback()` (simulation of crash).

```
var ironium = require('ironium');

ironium.scheduleJob('second', '1s', function(callback) {
  console.log("I run every second");
});

ironium.start();
```

I run server for 10 seconds, stop it, add `callback()` to the handler, and start it again.

The result is DoS of previously scheduled jobs that were meant to run every 1s at max:

```
I run every second
I run every second
I run every second
I run every second
I run every second
I run every second
```

If I set interval to `1s`, I'd expect this job will run every 1s at max. So if callback is not called, further schedules are dropped. Is there a way to achieve it?

**Comment by djanowski** [comment]
Minimum interval is 1 minute now, but this issue should be fixed in Ironium 5.0 (by https://github.com/assaf/ironium/pull/51).

Please report back if it's still an issue.

Thanks!
