### ISSUE TITLE
next param to queueJob doesn't exist

### ISSUE THREAD

**Issue by sheerun** [assaf/ironium#35]
Hey,

The readme says:

```
customer.on('save', function(next) {
  if (this.isNew)
    sendWelcomeEmail.queueJob(this.id, next);
  else
    next();
});
```

but the queueJob signature don't have callback as second param. maybe you forgot to fix docs.

**Comment by djanowski** [comment]
Yes, documentation bug. We upgraded Ironium to use promises now (and updated docs). Thank you.
