### ISSUE TITLE
Scheduled jobs with iron.io don't work properly

### ISSUE THREAD

**Issue by sheerun** [assaf/ironium#36]
I've created a simple worker that uses iron.io as backend:

```
var ironium = require('ironium');
var config = require('./iron.json');
ironium.configure(config);

ironium.scheduleJob('second', '1s', function(next) {
  console.log('scheduling');
  next();
});

ironium.start();
```

but when I run it, `scheduling` is displayed only once. I see processed message in ironmq, but only one first job is consumed. No next job is scheduled.

**Comment by assaf** [comment]
This is not `setInterval`, it's designed for jobs that run every few minutes/hours/days

**Comment by sheerun** [comment]
I'm quite sure it's the same with one minute interval

**Comment by djanowski** [comment]
@sheerun Can you please check if it's the same or not?

**Comment by djanowski** [comment]
@sheerun I confirmed your issue. It started to to happen when we added coordination for schedules. But in reality, Ironium was never designed for short intervals, so #46.
