### ISSUE TITLE
Unable to test if queue.delayJob has been processed

### ISSUE THREAD

**Issue by ugotsoul** [assaf/ironium#48]
Ironium version: `4.1.3`
Test suite: mocha `3.2.0`

Problem:
I'm trying to test `queue.delayJob` processes a job after X amount of delay. I'm using [timekeeper](https://github.com/vesln/timekeeper) to stub `Date and Date.now`.  After invoking `queue.delayJob` and `Ironium.runJobs()` in the test suite, these test(s) fail because the job is not processed. Beanstalkd checks the `delay` of a job against hte system time, but Timekeeper doesn't stub the system time.

Potential solution(s)?

- Use another library to stub the system time (eg, ionix) instead of Timekeeper. I started down this path and it was a bit complicated to implement.
- Set Ironium's delay based on the environment: for example, set it to `1s` in test, in dev/prod set to the actual delay time.
- Create a method in Ironium to inspect the queue, and find the job with the delay in one test. In another test, run the job without delay and check the if the job was processed correctly.

**Comment by assaf** [comment]
We're talking about running in a test environment, tweaking `Date.now`, and calling `runJobs()` to run all queued jobs. So why not have `runJobs` run all jobs based on the time they were scheduled to run, but skips jobs that are not scheduled to run yet?

**Comment by djanowski** [comment]
Assuming we want to continue using Beanstalkd for testing: I didn't find a way to inspect the delayed queue and get a timestamp related to the job (queued time, ready time, anything). There's age and time left before the job is ready, but without a reference to the time when the job was queued, those are not useful. We _could_ keep the timestamp of when the job was queued by Ironium, only in test mode, and use that to calculate whether the job is due or not after time traveling.

Assuming there's no compelling reason to keep using Beanstalkd for testing: We could write a simple backend to be used in test mode, everything in Node's memory, so affected by changes to `Date.now()`.

**Comment by assaf** [comment]
Test environment and backend are two different concerns, you can use any backend in either environment.

**Comment by ugotsoul** [comment]
>  We could keep the timestamp of when the job was queued by Ironium, only in test mode, and use that to calculate whether the job is due or not after time traveling.

This sounds interesting. How are you thinking of storing/accessing this timestamp in test mode? Would queueJob/delayJob return a promise that resolves to the jobID and the timestamp...?

**Comment by ugotsoul** [comment]
@assaf thoughts? I'm not sure how to go about solving this 🤔

**Comment by assaf** [comment]
> We could keep the timestamp of when the job was queued by Ironium, only in test mode, and use that to calculate whether the job is due or not after time traveling.
