### ISSUE TITLE
Beanstalkd webhook url is localhost only?

### ISSUE THREAD

**Issue by willvincent** [assaf/ironium#66]
Looking at the configuration.js, it appears that the assumption is that any webhook usage for beanstalkd would always access localhost. I'm not clear if this is an oversight, or indeed even an issue, but it strikes me as incorrect. Shouldn't the host in the WEBHOOK_LOCAL that's used for beanstalkd config use whatever beanstalkd host is specified?

Browsing the rest of the codebase it wasn't immediately apparent if the webhook url was actually necessary at all though.

Would appreciate some guidance on this, even if just to tell me it's really a non-issue :)

**Comment by assaf** [comment]
You can change the host and port. The default is localhost since Beanstalkd is not designed to be used over network connection (no encryption).

**Comment by willvincent** [comment]
I don't think you're thinking of what I'm referring to. Yes, I know that you can configure host and port, but as far as I can see in the configure.js file, there is no way to set the _webhook url_ for beanstalkd if you're using something other than localhost.

```
const IRONIO_WEBHOOKURL   = 'https://{host}/3/projects/{projectID}/queues/{queueName}/webhook?oauth={token}';
const LOCAL_WEBHOOKURL    = 'https://localhost/webhooks/queues/{queueName}/messages/webhook';

// snip

} else {
      // Beanstalkd
      this.host             = config.host || process.env.BEANSTALKD_HOSTNAME || BEANSTALKD_HOSTNAME;
      this.port             = config.port || process.env.BEANSTALKD_PORT     || BEANSTALKD_PORT;
      this._webhookURL      = LOCAL_WEBHOOKURL;
      this.service          = 'beanstalk';
    }

// snip

  webhookURL(queueName) {
    return this._webhookURL
        .replace('{host}',      this.host)
        .replace('{projectID}', this.project_id)
        .replace('{token}',     this.token)
        .replace('{queueName}', queueName);

  }
```

Host is only replaced in the webhook url if it's using the IRONIO webhook value.

As you said, since beanstalkd isn't designed to be used over a network connection, it may not really be an issue -- but suppose, for example, you had a beanstalkd server set up within a _private_ network, that the various services can talk to, but isn't accessible from outside, this could be a problem in that case, right?

**Comment by assaf** [comment]
IronMQ has a feature that allows sending jobs directly to the job queue using HTTP requests. This is a convenient method that determines the URL based on the project and queue name. Beanstalkd does not support webhooks.

**Comment by willvincent** [comment]
Ok, so then the answer is that it is in fact a non-issue. Got it. Thanks :)
